export default {
    ADD_TASK: 'ADD_TASK',
    HANDLE_STATUS: 'HANDLE_STATUS',
    HANDLE_CANCEL: 'HANDLE_CANCEL',
    HANDLE_OK: 'HANDLE_OK',
    FETCH_FLUME: 'FETCH_FLUME',
    FETCH_TASK: 'FETCH_TASK',
    MODIFY_TASK: 'MODIFY_TASK',
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL: 'HIDE_MODAL'
}